# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ "main" ]
env:
   TG_VER: 0.36.6



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: version
        run : terraform --version
  second:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
         terragrunt_version: ${{ env.TG_VER }}
  need_to_result:
    runs-on: ubuntu-latest
    needs: [build,second]
    if: |
      always() &&
      contains(needs.build.result, 'success') &&
      contains(needs.second.result, 'cancelled')
    steps:
      - uses: actions/checkout@v3
      - name: If first success and second canceled
        run: echo "Hello, world! try again"

