name: Build and Deploy Mini Environment

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target env'
        required: true
        type: choice
        default: 'sandbox'
        options:
        - production
        - sandbox        
env:
   AWS_DEFAULT_REGION: "us-east-1"
   TG_VER: 0.36.6
   TF_VER: 1.1.7
permissions:
   id-token: write
   contents: read

jobs:

###### Deploy ######
  deploy:
    name: Deploy to  environment ${{ github.event.inputs.env || inputs.account }}
    runs-on: ubuntu-latest
    steps:
            
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 3.89.127.45
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          git clone https://oauth2:${{ secrets.TOKEN }}@github.com/rightbound/rb-poc.git
          mkdir projects/rb-poc
          cp -r rb-poc/* projects/rb-poc


